### ISSUE TITLE
varconf make

### ISSUE THREAD

**Issue by ThePowerTool** [worldforge/varconf#7]
Hi, I am very new to this--I literally found WorldForge this week and am very excited.

FYI, I'm working on a fresh VM running Fedora 36.

I received notification from cyphesis that I needed the libraries so I downloaded them.  Atlas-C++-0.6.4 seems to have compiled smoothly.  varconf-1.0.1 kicks errors during make:

`In file included from config.cpp:27:
../varconf/config.h:97:52: error: ISO C++17 does not allow dynamic exception specifications
   97 |   void parseStream(std::istream & in, Scope scope) throw (ParseError);
      |                                                    ^~~~~
config.cpp: In function 'std::istream& varconf::operator>>(std::istream&, Config&)':
config.cpp:137:21: warning: catching polymorphic type 'class varconf::ParseError' by value [-Wcatch-value=]
  137 |   catch (ParseError p) {
      |                     ^
config.cpp: At global scope:
config.cpp:340:58: error: ISO C++17 does not allow dynamic exception specifications
  340 | void Config::parseStream(std::istream & in, Scope scope) throw (ParseError)
      |                                                          ^~~~~
config.cpp: In member function 'bool varconf::Config::readFromFile(const std::string&, varconf::Scope)':
config.cpp:543:21: warning: catching polymorphic type 'class varconf::ParseError' by value [-Wcatch-value=]
  543 |   catch (ParseError p) {
      |                     ^
make[2]: *** [Makefile:387: config.lo] Error 1
make[2]: Leaving directory '/home/cyphesis/WorldForge/varconf-1.0.1/varconf'
make[1]: *** [Makefile:404: all-recursive] Error 1
make[1]: Leaving directory '/home/cyphesis/WorldForge/varconf-1.0.1'
make: *** [Makefile:308: all] Error 2`

I checked and found (what I believe to be the problem):
`97   void parseStream(std::istream & in, Scope scope) throw (ParseError);`

but have no clue on subsequent errors.

Could someone please help?  I am really looking forward to getting this up-and-running.

**Comment by ThePowerTool** [comment]
Update:  Much was resolved by adding the CXXFLAGS="-std=c++14" flag to the make command.

For both Atlas and varconf (per instructions provided during the compile):
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

There is a problem with how configure isolates the version of pg_config which prevents configure from detecting pg_config > 7.1.  I resolved this with a quick and temporarly fix (I have no clue how versions are incremented so this may only work for this version):
`    psql_minor_version=`$PG_CONFIG $psql_args --version | sed 's/PostgreSQL \([0-9]*\).\([0-9]*\)\(.\([0-9]*\)\).*$/\1/'`
    psql_micro_version=`$PG_CONFIG $psql_config_args --version | sed 's/PostgreSQL \([0-9]*\).\([0-9]*\)\(.\([0-9]*\)\).*$/\1/'``
I'm not sure how this code snippet will appear and have no clue why github would use a code designator that conflicts with code.

This leaves me with what may be the final issue:
`

In file included from PythonScriptFactory.cpp:21:
--


<code><span class="n">make</span><span class="p">:</span> <span class="o">***</span> <span class="p">[</span><span class="n">Makefile</span><span class="p">:</span><span class="mi">445</span><span class="p">:</span> <span class="n">check</span><span class="o">-</span><span class="n">recursive</span><span class="p">]</span> <span class="n">Error</span> <span class="mi">1</span>
</code>`

The compile fails with errors.

Any help would be appreciated!  Thank you very much!

**Comment by erikogenvik** [comment]
Which version of Varconf did you get these issues with? I.e. did you use "master" or one of the tagged versions?

**Comment by ThePowerTool** [comment]
For this attempt I grabbed all tarballs from https://sourceforge.net/projects/worldforge/files/

The varconf is https://sourceforge.net/projects/worldforge/files/varconf (config lib)/1.0.1/varconf-1.0.1.tar.gz/download

a.k.a. https://sourceforge.net/projects/worldforge/files/varconf%20%28config%20lib%29/1.0.1/varconf-1.0.1.tar.gz/download

**Comment by erikogenvik** [comment]
Ah, good that you brought that to our attention. Those files haven't been updated in ages; that's why you're getting this error related to you using a newer compiler. These issues are fixed in the Git master branch though.

**Comment by ThePowerTool** [comment]
I'm glad I could, in some small way, help!  I won't be following-up on this anymore given your last post but will leave this for you to determine when to close.

Thank you!

**Comment by erikogenvik** [comment]
This should now build with Conan 2.
